version: "3.5"
services:

  mongodb:
    image: mongo
    working_dir: /mongodb
    volumes:
      - ./:/mongodb/data
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
    restart: always
    networks: 
      - qa-net  
  
  qa-app:
    image: qa-api
    depends_on: 
      - "mongodb"
    build: .
    ports:
      - "8080:8080"
      - "50051:50051"
    networks:
      - qa-net

networks:
  qa-net:
    name: qa-net