### Get All Questions
GET http://localhost:8080/question
Content-Type: application/json

### Get Question By ID
GET http://localhost:8080/question/2
Content-Type: application/json

### Get Question By User
GET http://localhost:8080/question/user/1
Content-Type: application/json

### Create Question
POST http://localhost:8080/question
Content-Type: application/json

{   
    "statement": "What is a microservice?",
    "userId": "1",
    "createdOn": 0
}

### Add answer to question
POST http://localhost:8080/question/answer
Content-Type: application/json

{   
    "anwser": "Yes this is a microservice",
    "userId": "1",
    "questionId": "2"
}

### Update Question And Answer
PUT http://localhost:8080/question/1
Content-Type: application/json

{
    "question": {
      "id": "1",
      "statement": "Do You Think That GOPHERS Rocks hard?",
      "userId": "1",
      "createdOn": 1630587411
    },
    "answer": {
      "id": "1",
      "anwser": "Yes they Do!",
      "questionId": "1",
      "userId": "2",
      "createdOn": 1630587411
    }
}

### Delete Question
DELETE http://localhost:8080/question/2
Content-Type: application/json