### Get All Questions
GET http://localhost:8080/question
Content-Type: application/json

### Get Question By ID
GET http://localhost:8080/question/229a58e6-25a5-49b1-a09d-56026bb42b9c
Content-Type: application/json

### Get Question By User
GET http://localhost:8080/question/user/1
Content-Type: application/json

### Create Question
POST http://localhost:8080/question
Content-Type: application/json

{   
    "statement": "What do you think about gRPC?",
    "userId": "1"
}

### Add answer to question
POST http://localhost:8080/question/answer
Content-Type: application/json

{   
    "anwser": "gRPC is a great way of handle internal microservice communication.",
    "userId": "22",
    "questionId": "21f78b65-6443-4377-8b48-9cb0fb398091"
}

### Update Question And Answer
PUT http://localhost:8080/question/c1ced94c-a190-4122-9849-5244b551218c
Content-Type: application/json

{
    "question": {
      "id": "c1ced94c-a190-4122-9849-5244b551218c",
      "statement": "Do you like programming in Go?",
      "userId": "1",
      "createdOn": 1630682081
    },
    "answer": {
      "id": "3258613d-344d-4fa3-aca0-d05dfa8d347f",
      "anwser": "Yes I love programming in Go!",
      "questionId": "c1ced94c-a190-4122-9849-5244b551218c",
      "userId": "2",
      "createdOn": 1630682112
    }
  }

### Delete Question
DELETE http://localhost:8080/question/8940b1fd-8bfe-4cd8-9360-d3ae3bb48074
Content-Type: application/json